export const CURRENT_YEAR = new Date().getFullYear();

export const SEARCH_FILTERS_FOR_USER = [
   {
      filter: 'keyword',
      text: 'Từ khoá bất kỳ',
   },
   {
      filter: 'title',
      text: 'Tựa đề',
   },
   {
      filter: 'author',
      text: 'Tác giả',
   },
   {
      filter: 'bookId',
      text: 'Mã số trên kệ',
   },
   {
      filter: 'publisher',
      text: 'Nhà xuất bản',
   },
   {
      filter: 'publishYear',
      text: 'Năm xuất bản',
   },
];

export const BOOK_TOPICS = [
   'An ninh mạng',
   'Blockchain',
   'Cấu trúc dữ liệu',
   'Công nghệ phần mềm',
   'Công nghệ thông tin',
   'Cơ sở dữ liệu',
   'Điện toán đám mây',
   'Đồ hoạ máy tính',
   'Giải thuật & thuật toán',
   'Khai phá dữ liệu',
   'Kiến trúc máy tính',
   'Lập trình Web / App',
   'Mạng máy tính',
   'Ngôn ngữ mô hình hoá',
   'Quản trị hệ thống',
   'Trí tuệ nhân tạo',
   'Tự động hoá',
];

export const BOOK_TYPES = ['Sách in', 'Luận văn', 'Nghiên cứu khoa học'];

export const DATA = [
   {
      topic: 'An ninh mạng',
      type: 'Sách in',
      publisher: 'Khoa học và Kỹ thuật',
      publishYear: 2004,
      bookId: '005.8 /Nh500 ',
      author: 'Phạm Minh Việt',
      title: 'An toàn thông tin : Mạng máy tính truyền số và truyền dữ liệu',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Luận văn',
      publisher: 'Khoa MMT & TT, Đại học Cần Thơ',
      publishYear: 2021,
      bookId: 'ĐH2021118',
      author: 'Nguyễn Thị Xuân Tươi - B1610703, GVHD: PGS. Đỗ Thanh Nghị',
      title: 'Studying Network Intrusions (Nghiên Cứu Tấn Công Mạng)',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Sách in',
      publisher: 'Kluwer Academic',
      publishYear: 1997,
      bookId: '005.8/K88 ',
      author: 'Weidong Kou',
      title: 'Networking security and standards',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Sách in',
      publisher: 'McGraw-Hill',
      publishYear: 2007,
      bookId: '658.0557585 /A139 ',
      author: 'Abel John',
      title: 'Oracle E- Business suite sericurty',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Sách in',
      publisher: 'Samsnet',
      publishYear: 1997,
      bookId: '005.8/A615 ',
      author: 'Nonymous',
      title: "Maximum security: A Hacker's guide to protecting your Internetsite and network",
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Sách in',
      publisher: 'Thống Kê',
      publishYear: 2003,
      bookId: '005.8 /M312 ',
      author: 'Minh Mẫn',
      title: 'Bảo mật trong Windows server 2003',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Sách in',
      publisher: 'Tổng hợp Thành phố Hồ Chí Minh, 2005',
      publishYear: 2005,
      bookId: '005.84/Th116 ',
      author: 'Trần Văn Thắng',
      title: 'Hướng dẫn học nhanh máy vi tính phòng chống Virút',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Sách in',
      publisher: 'Viện toán học',
      publishYear: 2004,
      bookId: '005.8 /Đ305 ',
      author: 'Phạm Huy Điển',
      title: 'Mã hóa thông tin : Cơ sở toán học và ứng dụng',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Sách in',
      publisher: 'Wiley',
      publishYear: 2006,
      bookId: '658.0558/L657 ',
      author: 'LeVeque, Vincent',
      title: 'Information security : A strategic approach',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Sách in',
      publisher: 'Wiley',
      publishYear: 2003,
      bookId: '005.8 /M423 ',
      author: 'Ngọc Tuấn',
      title: 'Mastering web services security',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH2021348',
      author: 'Mai Thị Trà My-B1706839, GVHD: TS. Thái Minh Tuấn',
      title: 'Phát hiện và phân loại mã độc trong tập tin APK trên hệ điều hành Android',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'An ninh mạng',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH2021704',
      author: 'Nguyễn Thị Ngọc Trâm-B1709373, GVHD: Đỗ Thanh Nghị',
      title: 'Nghiên cứu an ninh trên thiết bị IoT',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Luận văn',
      publisher: 'Khoa CNTT, Đại học Cần Thơ',
      publishYear: 2021,
      bookId: 'ĐH202135',
      author: 'Trần Minh Tài - B1606931, GVHD: TS. Trần Công Án',
      title: 'Xây dựng nền tảng quan trắc môi trường nước dựa trên công nghệ blockchain/Phân hệ: Ứng dụng mobile',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Nghiên cứu khoa học',
      publisher: 'Trường CNTT & TT, Đại học Cần Thơ',
      publishYear: 2021,
      bookId: 'THS2020-67',
      author: 'B1809707 - Nguyễn Chí Hoàng Minh',
      title: 'Bảo mật dữ liệu cho đám mây IoT dựa trên công nghệ Blockchain',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH2021484',
      author: 'Trương Quốc Thái-B1706641, GVHD: Trần Công Án',
      title: 'Xây dựng ứng dụng quản lý văn bằng dựa trên nền tảng Ethereum',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH2021482',
      author: 'Nguyễn Trọng Phúc-B1706744, GVHD: Trần Công Án',
      title: 'Xây dựng ứng dụng quản lý quyền sở hữu đất đai dựa trên công nghệ blockchain',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH2021492',
      author: 'Nguyễn Hoàng Duy-B1706681, GVHD: Trần Công Án',
      title: 'Ứng dụng công nghệ blockchain trong quản lý sổ khám bệnh',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH2021503',
      author: 'Luu Tran Anh Nhut-B1706624, GVHD: Thái Minh Tuấn',
      title: 'Quản Lý Chuỗi Cung Ứng Nông Sản Sử Dụng Công Nghệ Chuỗi Khối',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH2021513',
      author: 'Trương Ngọc Ánh-B1706446, GVHD: Trần Công Án',
      title: 'Xây dựng hệ thống đăng ký xe trực tuyến dựa trên công nghệ blockchain',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH2021515',
      author: 'Huỳnh Lê Tỷ-B1706892, GVHD: Trần Công Án',
      title: 'Xây dựng hệ thống đăng ký Căn cước công dân dựa trên công nghệ blockchain',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH202177',
      author: 'Lưu Quốc Trung - B1606948, GVHD: TS. Trần Công Án',
      title: 'Nghiên cứu phân quyền trong ƯD quản lý văn bằng dựa trên công nghệ blockchain',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Blockchain',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH202180',
      author: 'Nguyễn Văn Minh - B1607002, GVHD: TS. Lâm Hoài Bảo',
      title: 'Ứng dụng blockchain và QR code trong xây dựng và trích xuất thông tin',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Addison-Wesley',
      publishYear: 2004,
      bookId: '005.133/L673',
      author: 'ohn Lewis, Joseph Chase',
      title: 'Java Software structures : Designing and using data structures',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Addison-Wesley',
      publishYear: 2001,
      bookId: '005.133/B927',
      author: 'Timothy Budd',
      title: 'Classic data structures in Java',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Addison-Wesley',
      publishYear: 1994,
      bookId: '005.73 / K75',
      author: 'Koffman, Elliot B',
      title: 'Software design and data structures in turbo pascal',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Addison-Wesley',
      publishYear: 1998,
      bookId: '005.1/K55',
      author: 'Jeffrey H. Kingston',
      title: 'lgorithms and data structures : Design, correctness, analysis',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Benjamin/Cummings',
      publishYear: 1994,
      bookId: '005.1 / W429',
      author: 'Mark Allen Weiss',
      title: 'Data structure and algorithm analysis',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Đại học Quốc gia Hà Nội',
      publishYear: 2008,
      bookId: '005.73 / Nh300',
      author: 'Trần, Hạnh Nhi',
      title: 'Cấu trúc dữ liệu và giải thuật',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Đại học Quốc Gia Hà Nội',
      publishYear: 2010,
      bookId: '005.73/L452 ',
      author: 'Đỗ Xuân Lôi',
      title: 'Cấu trúc dữ liệu và giải thuật',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Ediscience',
      publishYear: 1994,
      bookId: '005.73/F929 ',
      author: 'Gaudel, Marie - Claude ;  Soria, Michèle',
      title: 'Types de données et algorithmes',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Giáo Dục',
      publishYear: 1995,
      bookId: '005.73 / C561',
      author: 'Hoàng Đức Hải',
      title: 'Cấu trúc dữ liệu + giải thuật chương trình',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Giáo Dục',
      publishYear: 2008,
      bookId: '005.133 / H561',
      author: 'Nguyễn, Việt Hương',
      title: 'Ngôn ngữ lập trình C++ và cấu trúc dữ liệu',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Giáo Dục',
      publishYear: 2005,
      bookId: '005.73 /L452 ',
      author: 'Đỗ Xuân Lôi',
      title: 'Giáo trình cấu trúc dữ liệu và giải thuật : (Sách dùng cho các trường đào tạo hệ Trung học chuyên nghiệp)',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Giáo Dục',
      publishYear: 2008,
      bookId: '005.133/H561',
      author: 'Nguyễn Việt Hương',
      title: 'Ngôn ngữ lập trình C++ và Cấu trúc dữ liệu',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Lao Động - Xã Hội',
      publishYear: 2000,
      bookId: '005.73/U65/T.3',
      author: 'Moon Hwang Up ; Nguyễn Thị Thanh Hồng (dịch)',
      title: 'Cấu trúc dữ liệu : Công nghệ xử lý thông tin',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'McGraw-Hill',
      publishYear: 1995,
      bookId: '005.73/M749',
      author: 'Alistair McMonnies, W. Stewart McSporran',
      title: 'Developing object-oriented data structures using C++',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Prentice Hall',
      publishYear: 1990,
      bookId: '005.73 / T292',
      author: 'Tenenbaum, Aaron M',
      title: 'Data structures using C',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Thống Kê',
      publishYear: 2003,
      bookId: '005.133/H876',
      author: 'John R. Hubbard; Minh Trung và Gia Việt biên dịch',
      title: '455 bài tập Cấu trúc dữ liệu: Ứng dụng và cài đặt bằng C++',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Thống Kê',
      publishYear: 2002,
      bookId: '005.133/Gi108',
      author: 'Nguyễn Tiến',
      title: 'Giáo trình Cấu trúc dữ liệu và giải thuật Java : Lập trình chuyên nghiệp cùng các chuyên gia',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Thống Kê',
      publishYear: '',
      bookId: '005.133 / Tr513',
      author: 'Lê Minh Trung',
      title: 'Thuật toán và cấu trúc dữ liệu cho Java',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Trường Đại học Bách khoa Tp. HCM',
      publishYear: 1994,
      bookId: '005.73 / Tr552',
      author: 'Nguyễn, Trung Trực',
      title: 'Cấu trúc dữ liệu',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Cấu trúc dữ liệu',
      type: 'Sách in',
      publisher: 'Wiley-Interscience',
      publishYear: 2007,
      bookId: '005.74 /P792 ',
      author: 'Ponniah Paulraj',
      title: 'Data modeling fundamentals : A practical guide for IT professionals',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Công nghệ phần mềm',
      type: 'Luận văn',
      publisher: '',
      publishYear: 2021,
      bookId: 'ĐH2021308',
      author: 'Lê Thị Thúy An-B1704710, GVHD: Nguyễn Công Danh',
      title: 'Ứng dụng mô hình Page Object Model kiểm thử tự động cho website bán hàng trực tuyến',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Công nghệ phần mềm',
      type: 'Sách in',
      publisher: 'Addison-Wesley',
      publishYear: 2004,
      bookId: '005.1/M267 ',
      author: 'Manassis, Enricos',
      title: 'Practical software engineering : Analysis and design for the .NET platform',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Công nghệ phần mềm',
      type: 'Sách in',
      publisher: 'Addison-Wesley',
      publishYear: 2006,
      bookId: '005.1/F791 ',
      author: 'Fox, Christopher',
      title: 'Introduction to software engineering design : Processes, principles, and patterns with UML2',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Công nghệ phần mềm',
      type: 'Sách in',
      publisher: 'Addison-Wesley',
      publishYear: 2001,
      bookId: '005.1/S697 ',
      author: 'Sommerville, Ian',
      title: 'Software engineering',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Công nghệ phần mềm',
      type: 'Sách in',
      publisher: 'Đại học Cần Thơ',
      publishYear: '',
      bookId: '005.1/H307 ',
      author: 'Huỳnh, Xuân Hiệp',
      title: 'Bài giảng nhập môn công nghệ phần mềm = Course of introduction to software engineering: Course of introduction to software engineering',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Tự động hoá',
      type: 'Nghiên cứu khoa học',
      publisher: 'Đại học Cần Thơ',
      publishYear: 2020,
      bookId: '629.895 / Kh106',
      author: 'Trần Vi Khang',
      title: 'Ứng dụng mạng cảm biến xây dựng hệ thống giám sát nhiệt độ kho lạnh trong không gian ba chiều',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Công nghệ phần mềm',
      type: 'Sách in',
      publisher: 'Giáo Dục',
      publishYear: 2001,
      bookId: '005.1/P935/T.2 ',
      author: 'Ngô Việt Trung - Dịch',
      title: 'Kĩ thuật phần mềm : Cách tiếp cận của người thực hành. Tập 2',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Công nghệ phần mềm',
      type: 'Sách in',
      publisher: 'Giáo Dục',
      publishYear: 2008,
      bookId: '005.1/C561 ',
      author: 'Thạc Bình Cường',
      title: 'Nhập môn công nghệ phần mềm',
      description: 'Chưa có mô tả',
   },
   {
      topic: 'Công nghệ phần mềm',
      type: 'Sách in',
      publisher: 'IEEE Computer Society Press',
      publishYear: 2000,
      bookId: '005.1/S676 ',
      author: 'Dorfman, M. - Editor ;  Thayer, Richard H. - Editor',
      title: 'Software engineering',
      description: 'Chưa có mô tả',
   },
];

export const BOOK_TABLE_HEADERS = {
   title: 'Tựa đề',
   description: 'Mô tả',
   bookId: 'Mã số trên kệ',
   type: 'Phân loại',
   topic: 'Chủ đề',
   author: 'Tác giả',
   publisher: 'Nhà xuất bản',
   publishYear: 'Năm xuất bản',
   createdAt: 'Tạo lúc',
   updatedAt: 'Cập nhật lúc',
};

export const BOOK_SORT_BY = [
   {
      text: 'Tựa đề',
      value: 'title',
   },
   {
      text: 'Mã số trên kệ',
      value: 'bookId',
   },
   {
      text: 'Phân loại',
      value: 'type',
   },
   {
      text: 'Chủ đề',
      value: 'topic',
   },
   {
      text: 'Tác giả',
      value: 'author',
   },
   {
      text: 'Nhà xuất bản',
      value: 'publisher',
   },
   {
      text: 'Năm xuất bản',
      value: 'publishYear',
   },
   {
      text: 'Thời gian tạo',
      value: 'createdAt',
   },
   {
      text: 'Thời gian chỉnh sửa',
      value: 'updatedAt',
   },
];

export const SORT_TYPE = [
   {
      text: 'Tăng dần (A-Z)',
      value: 1,
   },
   {
      text: 'Giảm dần (Z-A)',
      value: -1,
   },
];

export const USER_TABLE_HEADERS = {
   userId: 'Tên đăng nhập',
   password: 'Mật khẩu',
   username: 'Họ và tên',
   birthday: 'Ngày sinh',
   gender: 'Giới tính',
   role: 'Quyền',
   faculty: 'Khoa',
   class: 'Lớp',
   isBlocked: 'Tài khoản bị khoá?',
   passwordChangedAt: 'Mật khẩu thay đổi lúc',
   createdAt: 'Tạo lúc',
   updatedAt: 'Cập nhật lúc',
};

export const USER_SORT_BY = [
   {
      text: 'Tên đăng nhập',
      value: 'userId',
   },
   {
      text: 'Họ và tên',
      value: 'username',
   },
   {
      text: 'Ngày sinh',
      value: 'birthday',
   },
   {
      text: 'Khoa',
      value: 'faculty',
   },
   {
      text: 'Lớp',
      value: 'class',
   },
   {
      text: 'Thời gian thay đổi mật khẩu',
      value: 'passwordChangedAt',
   },
   {
      text: 'Thời gian tạo',
      value: 'createdAt',
   },
   {
      text: 'Thời gian chỉnh sửa',
      value: 'updatedAt',
   },
];
